
package itson.org.ghosttracks.utilerias;

import itson.org.ghosttracks.controladores.ControlVentaEnLinea;
import itson.org.ghosttracks.dtos.ProductoDTO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author emyla
 */
public class pnlProductoCatalogo extends javax.swing.JPanel {

    private ProductoDTO producto;
    private ControlVentaEnLinea control;
    
    /**
     * Creates new form pnlProductoCatalogo
     */
    public pnlProductoCatalogo(ProductoDTO producto, ControlVentaEnLinea control) {
        initComponents();
        this.producto = producto;
        this.control = control;
        
        lblNombreProducto.setText(producto.getNombre());
        lblArtista.setText(producto.getArtista());
        lblPrecio.setText("$" + producto.getPrecio());
        
        
        try {
            String nombreArchivo = producto.getImgProducto();
            
            String ruta = "/imgCatalogo/" + nombreArchivo;
            
            if (ruta != null && !ruta.isEmpty()) {
                java.net.URL urlImagenLocal = getClass().getResource(ruta);
                
                if (urlImagenLocal != null) {
                    java.awt.Image imagenOriginal = javax.imageio.ImageIO.read(urlImagenLocal);
                    
                    java.awt.Image imagenEscalada = imagenOriginal.getScaledInstance(180, 175, java.awt.Image.SCALE_SMOOTH);
                    
                    lblImg.setIcon(new javax.swing.ImageIcon(imagenEscalada));
                    lblImg.setText(""); 
                } else {
                    throw new Exception("Ruta no encontrada: " + ruta);
                }
            }
        } catch (Exception e) {
            System.out.println("Error cargando imagen de: " + producto.getNombre() + " - " + e.getMessage());
            lblImg.setIcon(null);
            lblImg.setText("Imagen no disp.");
        }
        this.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                control.irADetalleProducto(producto);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProducto = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        pnlImgProduct = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblImg = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 229, 222));

        pnlProducto.setBackground(new java.awt.Color(217, 217, 217));
        pnlProducto.setMaximumSize(new java.awt.Dimension(247, 351));

        pnlImgProduct.setBackground(new java.awt.Color(230, 230, 230));

        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlImgProductLayout = new javax.swing.GroupLayout(pnlImgProduct);
        pnlImgProduct.setLayout(pnlImgProductLayout);
        pnlImgProductLayout.setHorizontalGroup(
            pnlImgProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImgProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlImgProductLayout.setVerticalGroup(
            pnlImgProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImgProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblNombreProducto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNombreProducto.setText("Nombre Producto");

        lblArtista.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblArtista.setText("NombreArtista");

        lblPrecio.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblPrecio.setText("$00.00");

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlImgProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlImgProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreProducto)
                .addGap(18, 18, 18)
                .addComponent(lblArtista)
                .addGap(34, 34, 34)
                .addComponent(lblPrecio)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecio;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlImgProduct;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlProducto;
    // End of variables declaration//GEN-END:variables
}
