/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.utilerias;

import itson.org.ghosttracks.controladores.ControlVentaEnLinea;
import itson.org.ghosttracks.dtos.ProductoDTO;
import static java.awt.SystemColor.control;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author emyla
 */
public class pnlProductoSugerencia extends javax.swing.JPanel {

    
    private ProductoDTO producto;
    private ControlVentaEnLinea control;
    /**
     * Creates new form pnlSugerencias
     */
    public pnlProductoSugerencia(ProductoDTO producto, ControlVentaEnLinea control) {
        initComponents();
        this.producto = producto;
        this.control = control;
        
        setDatosSugerencia(this.producto);

        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                control.irADetalleProducto(producto);
            }
        });
    }

    public void setDatosSugerencia(ProductoDTO producto) {
        if (producto != null) {
            lblProductSug01.setText(producto.getNombre());
            lblArtistSug01.setText(producto.getArtista());
            lblPrecioSug01.setText(String.format("$%.2f", producto.getPrecio()));
            
            try {
                String nombreArchivo = producto.getImgProducto();

                String ruta = "/imgCatalogo/" + nombreArchivo;

                if (ruta != null && !ruta.isEmpty()) {
                    java.net.URL urlImagenLocal = getClass().getResource(ruta);

                    if (urlImagenLocal != null) {
                        java.awt.Image imagenOriginal = javax.imageio.ImageIO.read(urlImagenLocal);

                        java.awt.Image imagenEscalada = imagenOriginal.getScaledInstance(180, 175, java.awt.Image.SCALE_SMOOTH);

                        lblImg.setIcon(new javax.swing.ImageIcon(imagenEscalada));
                        lblImg.setText(""); 
                    } else {
                        throw new Exception("Ruta no encontrada: " + ruta);
                    }
                }
            } catch (Exception e) {
                System.out.println("Error cargando imagen de: " + producto.getNombre() + " - " + e.getMessage());
                lblImg.setIcon(null);
                lblImg.setText("Imagen no disp.");
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRedondeado1 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        pnlImgSug01 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblImg = new javax.swing.JLabel();
        lblProductSug01 = new javax.swing.JLabel();
        lblArtistSug01 = new javax.swing.JLabel();
        lblPrecioSug01 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(217, 217, 217));

        panelRedondeado1.setBackground(new java.awt.Color(230, 230, 230));

        lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlImgSug01Layout = new javax.swing.GroupLayout(pnlImgSug01);
        pnlImgSug01.setLayout(pnlImgSug01Layout);
        pnlImgSug01Layout.setHorizontalGroup(
            pnlImgSug01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImgSug01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlImgSug01Layout.setVerticalGroup(
            pnlImgSug01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImgSug01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblProductSug01.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblProductSug01.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductSug01.setText("Producto Sugerido 01");

        lblArtistSug01.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblArtistSug01.setForeground(new java.awt.Color(102, 102, 102));
        lblArtistSug01.setText("Artista 01");

        lblPrecioSug01.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblPrecioSug01.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecioSug01.setText("$00.00");

        javax.swing.GroupLayout panelRedondeado1Layout = new javax.swing.GroupLayout(panelRedondeado1);
        panelRedondeado1.setLayout(panelRedondeado1Layout);
        panelRedondeado1Layout.setHorizontalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioSug01, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addGroup(panelRedondeado1Layout.createSequentialGroup()
                        .addGroup(panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlImgSug01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProductSug01, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(lblArtistSug01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRedondeado1Layout.setVerticalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlImgSug01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblProductSug01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblArtistSug01)
                .addGap(26, 26, 26)
                .addComponent(lblPrecioSug01)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblArtistSug01;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPrecioSug01;
    private javax.swing.JLabel lblProductSug01;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado1;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlImgSug01;
    // End of variables declaration//GEN-END:variables
}
