/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.utilerias;

import itson.org.ghosttracks.dtos.CarritoDTO;
import itson.org.ghosttracks.dtos.ItemCarritoDTO;
import itson.org.ghosttracks.dtos.ProductoDTO;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author Nahomi FIgueroa
 */
public class pnlResumenPedido extends javax.swing.JPanel {

    private JPanel pnlLista;
    /**
     * Creates new form pnlResumenPedido
     */
    public pnlResumenPedido() {
        initComponents();
        pnlLista = new JPanel();
        pnlLista.setLayout(new BoxLayout(pnlLista, BoxLayout.Y_AXIS));
        pnlLista.setBackground(new java.awt.Color(217, 217, 217)); 
        jspProductosCarrito.setViewportView(pnlLista);
        jspProductosCarrito.setBorder(null); 
    }
    
    public void cargarResumen(CarritoDTO carrito) {
        pnlLista.removeAll();
        // carrito.calcularTotalGeneral();
        if (carrito.getProductos() != null) {
            for (ItemCarritoDTO item : carrito.getProductos()) {
                ProductoDTO prod = item.getProductoSeleccionado();
                Integer cant = item.getCantidad() != null ? item.getCantidad() : 0;
                pnllResumenProducto tarjeta = new pnllResumenProducto(prod, cant);
                pnlLista.add(tarjeta);
            }
        }

        lblSubtotalDisplay2.setText(String.format("$%.2f", carrito.getSubtotal()));
        lblTaxDisplay.setText(String.format("$%.2f", carrito.getImpuestos()));
        lblTotalDisplay.setText(String.format("$%.2f", carrito.getTotal()));
        
        pnlLista.revalidate();
        pnlLista.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalResumen = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblImgCarrito = new javax.swing.JLabel();
        lblResumen = new javax.swing.JLabel();
        pnlDisplayItems = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jspProductosCarrito = new javax.swing.JScrollPane();
        lblTaxDisplay = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblSubtotal1 = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblTotalDisplay = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblSubtotalDisplay2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(237, 229, 222));
        setPreferredSize(new java.awt.Dimension(348, 680));

        pnlPrincipalResumen.setBackground(new java.awt.Color(217, 217, 217));
        pnlPrincipalResumen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgCarrito.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblImgCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoCarrito.png"))); // NOI18N
        pnlPrincipalResumen.add(lblImgCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        lblResumen.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        lblResumen.setText("Resumen");
        pnlPrincipalResumen.add(lblResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        pnlDisplayItems.setBackground(new java.awt.Color(217, 217, 217));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        jspProductosCarrito.setBackground(new java.awt.Color(217, 217, 217));

        javax.swing.GroupLayout pnlDisplayItemsLayout = new javax.swing.GroupLayout(pnlDisplayItems);
        pnlDisplayItems.setLayout(pnlDisplayItemsLayout);
        pnlDisplayItemsLayout.setHorizontalGroup(
            pnlDisplayItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisplayItemsLayout.createSequentialGroup()
                .addComponent(jspProductosCarrito, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnlDisplayItemsLayout.setVerticalGroup(
            pnlDisplayItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDisplayItemsLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspProductosCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPrincipalResumen.add(pnlDisplayItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 350, 430));

        lblTaxDisplay.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lblTaxDisplay.setForeground(new java.awt.Color(102, 102, 102));
        lblTaxDisplay.setText("$0");
        pnlPrincipalResumen.add(lblTaxDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, -1, -1));

        lblTotal.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lblTotal.setText("Total");
        pnlPrincipalResumen.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        lblSubtotal1.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lblSubtotal1.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtotal1.setText("Subtotal:");
        pnlPrincipalResumen.add(lblSubtotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        lblTax.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lblTax.setForeground(new java.awt.Color(102, 102, 102));
        lblTax.setText("Tax(16%)");
        pnlPrincipalResumen.add(lblTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        lblTotalDisplay.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lblTotalDisplay.setText("$0");
        pnlPrincipalResumen.add(lblTotalDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        pnlPrincipalResumen.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 340, 10));

        lblSubtotalDisplay2.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lblSubtotalDisplay2.setText("$0");
        pnlPrincipalResumen.add(lblSubtotalDisplay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipalResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipalResumen, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JScrollPane jspProductosCarrito;
    private javax.swing.JLabel lblImgCarrito;
    private javax.swing.JLabel lblResumen;
    private javax.swing.JLabel lblSubtotal1;
    private javax.swing.JLabel lblSubtotalDisplay2;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTaxDisplay;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalDisplay;
    private javax.swing.JPanel pnlDisplayItems;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlPrincipalResumen;
    // End of variables declaration//GEN-END:variables
}
