/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.utilerias;

import itson.org.ghosttracks.controladores.ControlVentaEnLinea;
import itson.org.ghosttracks.dtos.ItemCarritoDTO;
import itson.org.ghosttracks.dtos.PedidoDTO;
import itson.org.ghosttracks.dtos.ProductoDTO;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.BoxLayout;

/**
 *
 * @author nafbr
 */
public class pnlResumenPedidoConfirmado extends javax.swing.JPanel {
    private final ControlVentaEnLinea control;
    /**
     * Creates new form pnlResumenPedidoConfirmado
     */
    public pnlResumenPedidoConfirmado(ControlVentaEnLinea control) {
        initComponents();
        this.control = control;
    }

    
    public void cargarDatosPedido(PedidoDTO pedido) {
        if (pedido == null) return;

        lblNumPedidoDisplay.setText("#" + pedido.getIdPedido());
        
        if (pedido.getCarrito() != null) {
            lblSubtotalDisplay.setText(String.format("$%.2f", pedido.getCarrito().getSubtotal()));
            lblImpuestosDisplay.setText(String.format("$%.2f", pedido.getCarrito().getImpuestos()));
            
            lblEnvioDisplay.setText(String.format("$%.2f", pedido.getCostoEnvio())); 
            lblTotalDisplay.setText(String.format("$%.2f", pedido.getCarrito().getTotal()));
            
            
            pnlResumenPedido.setLayout(new javax.swing.BoxLayout(pnlResumenPedido, javax.swing.BoxLayout.X_AXIS));
            pnlResumenPedido.removeAll(); 

            pnlResumenPedido.add(Box.createRigidArea(new Dimension(10, 0)));
            
            if (pedido.getCarrito().getProductos() != null) {
                for (ItemCarritoDTO item : pedido.getCarrito().getProductos()) {
                  
                    ProductoDTO prod = item.getProductoSeleccionado();
                    Integer cant = item.getCantidad() != null ? item.getCantidad() : 0;
                    pnllResumenProducto tarjeta = new pnllResumenProducto(prod, cant);
                    pnlResumenPedido.add(tarjeta);
                    pnlResumenPedido.add(Box.createRigidArea(new Dimension(15, 0)));
                }
            }
            
            pnlResumenPedido.revalidate();
            pnlResumenPedido.repaint();
        }

        
        if (pedido.getContacto() != null) {
            lblNombre.setText(pedido.getContacto().getNombre());
        } else {
            lblNombre.setText("Sin nombre");
        }

        if (pedido.getDireccionEntrega() != null) {
            itson.org.ghosttracks.dtos.DireccionEntregaDTO dir = pedido.getDireccionEntrega();
            lblCalle.setText(dir.getCalle() != null ? dir.getCalle() : "Calle no registrada");
            lblNumero.setText(dir.getNumero() != null ? "#" + dir.getNumero() : "S/N");
            lblColonia.setText(dir.getColonia() != null ? dir.getColonia() : "");
            lblCiudad.setText(dir.getCiudad() != null ? dir.getCiudad() : "Ciudad no registrada");
            lblEstado.setText(dir.getEstado()); 
            lblCodigoPostal.setText(dir.getCodigoPostal() != null ? "CP: " + dir.getCodigoPostal() : "");
        } else {
            lblCalle.setText("Recoger en sucursal");
            lblNumero.setText("");
            lblColonia.setText("");
            lblCiudad.setText("");
            lblEstado.setText("");
            lblCodigoPostal.setText("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlResumenPedidoConfirmado = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblResumenPedido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNumPedido = new javax.swing.JLabel();
        lblNumPedidoDisplay = new javax.swing.JLabel();
        lblPreparandoPedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlResumenPedido = new javax.swing.JPanel();
        lblResumenPedidoDinero = new javax.swing.JLabel();
        lblMetodoPagoDisplay = new javax.swing.JLabel();
        lblMetodoPago = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblImpuestos = new javax.swing.JLabel();
        lblEnvio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblSubtotalDisplay = new javax.swing.JLabel();
        lblImpuestosDisplay = new javax.swing.JLabel();
        lblEnvioDisplay = new javax.swing.JLabel();
        lblTotalDisplay = new javax.swing.JLabel();
        lblPedidoRecibido = new javax.swing.JLabel();
        pnlResumenEnvio = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblDireccionEnvio = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblEnviar = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCalle = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblColonia = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblCodigoPostal = new javax.swing.JLabel();
        btnComprarDeNuevo = new itson.org.ghosttracks.utilerias.BotonRedondeado();

        setBackground(new java.awt.Color(237, 229, 222));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlResumenPedidoConfirmado.setBackground(new java.awt.Color(208, 208, 208));

        lblResumenPedido.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblResumenPedido.setText("Resumen del pedido");

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        lblNumPedido.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        lblNumPedido.setText("No. Pedido");

        lblNumPedidoDisplay.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        lblNumPedidoDisplay.setText("#0000");

        lblPreparandoPedido.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        lblPreparandoPedido.setText("Preparando pedido");

        pnlResumenPedido.setBackground(new java.awt.Color(208, 208, 208));

        javax.swing.GroupLayout pnlResumenPedidoLayout = new javax.swing.GroupLayout(pnlResumenPedido);
        pnlResumenPedido.setLayout(pnlResumenPedidoLayout);
        pnlResumenPedidoLayout.setHorizontalGroup(
            pnlResumenPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        pnlResumenPedidoLayout.setVerticalGroup(
            pnlResumenPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlResumenPedido);

        lblResumenPedidoDinero.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        lblResumenPedidoDinero.setText("Resumen pedido:");

        lblMetodoPagoDisplay.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblMetodoPagoDisplay.setText("Método pago");

        lblMetodoPago.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        lblMetodoPago.setText("Método pago:");

        lblSubtotal.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblSubtotal.setText("Subtotal:");

        lblImpuestos.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblImpuestos.setText("Impuestos:");

        lblEnvio.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblEnvio.setText("Envío:");

        lblTotal.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblTotal.setText("Total:");

        lblSubtotalDisplay.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblSubtotalDisplay.setText("$0");

        lblImpuestosDisplay.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblImpuestosDisplay.setText("$0");

        lblEnvioDisplay.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblEnvioDisplay.setText("$0");

        lblTotalDisplay.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblTotalDisplay.setText("$0");

        javax.swing.GroupLayout pnlResumenPedidoConfirmadoLayout = new javax.swing.GroupLayout(pnlResumenPedidoConfirmado);
        pnlResumenPedidoConfirmado.setLayout(pnlResumenPedidoConfirmadoLayout);
        pnlResumenPedidoConfirmadoLayout.setHorizontalGroup(
            pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnlResumenPedidoConfirmadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResumenPedido)
                    .addGroup(pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlResumenPedidoConfirmadoLayout.createSequentialGroup()
                            .addComponent(lblMetodoPago)
                            .addGap(114, 114, 114)
                            .addComponent(lblMetodoPagoDisplay))
                        .addComponent(lblPreparandoPedido)
                        .addGroup(pnlResumenPedidoConfirmadoLayout.createSequentialGroup()
                            .addComponent(lblNumPedido)
                            .addGap(34, 34, 34)
                            .addComponent(lblNumPedidoDisplay))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblResumenPedidoDinero)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResumenPedidoConfirmadoLayout.createSequentialGroup()
                            .addGroup(pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSubtotal)
                                .addComponent(lblImpuestos)
                                .addComponent(lblEnvio)
                                .addComponent(lblTotal))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTotalDisplay)
                                .addComponent(lblEnvioDisplay)
                                .addComponent(lblImpuestosDisplay)
                                .addComponent(lblSubtotalDisplay))
                            .addGap(16, 16, 16))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlResumenPedidoConfirmadoLayout.setVerticalGroup(
            pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResumenPedidoConfirmadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblResumenPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPedido)
                    .addComponent(lblNumPedidoDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreparandoPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResumenPedidoConfirmadoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblMetodoPagoDisplay))
                    .addGroup(pnlResumenPedidoConfirmadoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblMetodoPago)))
                .addGap(18, 18, 18)
                .addComponent(lblResumenPedidoDinero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(lblSubtotalDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImpuestos)
                    .addComponent(lblImpuestosDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnvio)
                    .addComponent(lblEnvioDisplay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResumenPedidoConfirmadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalDisplay))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(pnlResumenPedidoConfirmado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 660, 520));

        lblPedidoRecibido.setFont(new java.awt.Font("Corbel", 0, 36)); // NOI18N
        lblPedidoRecibido.setText("¡Pedido recibido!");
        add(lblPedidoRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        pnlResumenEnvio.setBackground(new java.awt.Color(208, 208, 208));

        lblDireccionEnvio.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblDireccionEnvio.setText("Dirección de envío");

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));

        lblEnviar.setFont(new java.awt.Font("Corbel", 1, 22)); // NOI18N
        lblEnviar.setText("Enviar a:");

        lblNombre.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblNombre.setText("Nombre");

        lblCalle.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblCalle.setText("Calle");

        lblNumero.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblNumero.setText("Número");

        lblColonia.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblColonia.setText("Colonia");

        lblCiudad.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblCiudad.setText("Ciudad");

        lblEstado.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblEstado.setText("Estado");

        lblCodigoPostal.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblCodigoPostal.setText("Código postal");

        javax.swing.GroupLayout pnlResumenEnvioLayout = new javax.swing.GroupLayout(pnlResumenEnvio);
        pnlResumenEnvio.setLayout(pnlResumenEnvioLayout);
        pnlResumenEnvioLayout.setHorizontalGroup(
            pnlResumenEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(pnlResumenEnvioLayout.createSequentialGroup()
                .addGroup(pnlResumenEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResumenEnvioLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblDireccionEnvio))
                    .addGroup(pnlResumenEnvioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlResumenEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblEnviar)
                            .addGroup(pnlResumenEnvioLayout.createSequentialGroup()
                                .addComponent(lblCalle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumero))
                            .addComponent(lblColonia)
                            .addGroup(pnlResumenEnvioLayout.createSequentialGroup()
                                .addComponent(lblCiudad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEstado))
                            .addComponent(lblCodigoPostal))))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        pnlResumenEnvioLayout.setVerticalGroup(
            pnlResumenEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResumenEnvioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblDireccionEnvio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResumenEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalle)
                    .addComponent(lblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblColonia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlResumenEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudad)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCodigoPostal)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        add(pnlResumenEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 410, -1));

        btnComprarDeNuevo.setBackground(new java.awt.Color(191, 64, 43));
        btnComprarDeNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnComprarDeNuevo.setText("Volver a Comprar");
        btnComprarDeNuevo.addActionListener(this::btnComprarDeNuevoActionPerformed);
        add(btnComprarDeNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 290, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarDeNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarDeNuevoActionPerformed
        control.irAInicio();
    }//GEN-LAST:event_btnComprarDeNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnComprarDeNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCodigoPostal;
    private javax.swing.JLabel lblColonia;
    private javax.swing.JLabel lblDireccionEnvio;
    private javax.swing.JLabel lblEnviar;
    private javax.swing.JLabel lblEnvio;
    private javax.swing.JLabel lblEnvioDisplay;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblImpuestos;
    private javax.swing.JLabel lblImpuestosDisplay;
    private javax.swing.JLabel lblMetodoPago;
    private javax.swing.JLabel lblMetodoPagoDisplay;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumPedido;
    private javax.swing.JLabel lblNumPedidoDisplay;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPedidoRecibido;
    private javax.swing.JLabel lblPreparandoPedido;
    private javax.swing.JLabel lblResumenPedido;
    private javax.swing.JLabel lblResumenPedidoDinero;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalDisplay;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalDisplay;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlResumenEnvio;
    private javax.swing.JPanel pnlResumenPedido;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlResumenPedidoConfirmado;
    // End of variables declaration//GEN-END:variables
}
