/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.presentacion.administrador;

import itson.org.ghosttracks.controladores.ControladorVentasAdmin;
import itson.org.ghosttracks.dtos.PedidoDTO;

/**
 *
 * @author nafbr
 */
public class PanelDatosPaquete extends javax.swing.JPanel {

    private final ControladorVentasAdmin control;
    private final PedidoDTO pedido;
    
    /**
     * Creates new form PanelConfirmarEmpaquetado
     */
    public PanelDatosPaquete(ControladorVentasAdmin ctrl, PedidoDTO pedido) {
        this.control = ctrl;
        this.pedido = pedido;
        initComponents();
        lblCliente.setText(pedido.getCliente().getNombres());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnvia = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblInstrucciones = new javax.swing.JLabel();
        btnConfirmarEnvio = new itson.org.ghosttracks.utilerias.BotonRedondeado();

        setBackground(new java.awt.Color(237, 229, 222));

        lblEnvia.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lblEnvia.setText("Por favor, envia el pedido de");

        lblCliente.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setText("Cliente");

        lblInstrucciones.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lblInstrucciones.setText("Una vez enviado, ingresa los datos  y presiona \"Confirmar envío\"");

        btnConfirmarEnvio.setBackground(new java.awt.Color(191, 64, 43));
        btnConfirmarEnvio.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarEnvio.setText("Confirmar envío");
        btnConfirmarEnvio.addActionListener(this::btnConfirmarEnvioActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnvia)
                            .addComponent(btnConfirmarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(lblCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblInstrucciones)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblEnvia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInstrucciones)
                .addGap(143, 143, 143)
                .addComponent(btnConfirmarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEnvioActionPerformed
        control.despacharPedidoConSkydropx(this.pedido);
        control.volverAVentas();
    }//GEN-LAST:event_btnConfirmarEnvioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnConfirmarEnvio;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEnvia;
    private javax.swing.JLabel lblInstrucciones;
    // End of variables declaration//GEN-END:variables
}
