/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itson.org.ghosttracks.presentacion.administrador;

import itson.org.ghosttracks.controladores.ControladorVentasAdmin;
import itson.org.ghosttracks.dtos.PedidoDTO;
import static itson.org.ghosttracks.enums.EstadoPedidoDTO.EN_PREPARACION;
import javax.swing.JOptionPane;

/**
 *
 * @author nafbr
 */
public class PanelConfirmarEmpaquetado extends javax.swing.JPanel {

    private final ControladorVentasAdmin control;
   
    private final PedidoDTO pedido;
    
    /**
     * Creates new form PanelConfirmarEmpaquetado
     */
    public PanelConfirmarEmpaquetado(ControladorVentasAdmin ctrl, PedidoDTO pedido) {
        this.control = ctrl;
        this.pedido = pedido;
        initComponents();
        lblCliente.setText(pedido.getCliente().getNombres());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPreparaPedido = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblConfirmarPaquete = new javax.swing.JLabel();
        btnConfirmarPaquete = new itson.org.ghosttracks.utilerias.BotonRedondeado();

        setBackground(new java.awt.Color(237, 229, 222));

        lblPreparaPedido.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lblPreparaPedido.setText("Por favor, prepara el pedido de");

        lblCliente.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setText("Cliente");

        lblConfirmarPaquete.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        lblConfirmarPaquete.setText("Un a vez listo,  presiona \"confirmar empaque\"");

        btnConfirmarPaquete.setBackground(new java.awt.Color(191, 64, 43));
        btnConfirmarPaquete.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarPaquete.setText("Confirmar Empaque");
        btnConfirmarPaquete.addActionListener(this::btnConfirmarPaqueteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblPreparaPedido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(lblCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lblConfirmarPaquete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnConfirmarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(lblPreparaPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConfirmarPaquete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPaqueteActionPerformed
       control.actualizarEstadoPedido(this.pedido, EN_PREPARACION);
        JOptionPane.showMessageDialog(this, "Estado de pedido actualizado");
       control.volverAVentas();
    }//GEN-LAST:event_btnConfirmarPaqueteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnConfirmarPaquete;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblConfirmarPaquete;
    private javax.swing.JLabel lblPreparaPedido;
    // End of variables declaration//GEN-END:variables
}
