
package itson.org.ghosttracks.presentacion.administrador;

import itson.org.ghosttracks.controladores.ControladorVentasAdmin;
import itson.org.ghosttracks.dtos.ItemCarritoDTO;
import itson.org.ghosttracks.dtos.PedidoDTO;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oliro
 */
public class PantallaVentas extends javax.swing.JPanel {
    
    private final ControladorVentasAdmin control;
    private final String PLACEHOLDER_TEXT = "Nombre del cliente...";
    
    public PantallaVentas(ControladorVentasAdmin ctrl) {
        this.control = ctrl;
        initComponents();
        configurarFiltros();
        configurarEventosTabla();
        configurarPlaceholder();
        control.llenarTablaPedidos(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        panelFiltros = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        txxNombreCliente = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        btnBuscar = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        cmbxEstados = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        pnlDetallesPedido1 = new itson.org.ghosttracks.utilerias.pnlDetallesPedido();
        btnActualizarPedido = new itson.org.ghosttracks.utilerias.BotonRedondeado();

        setPreferredSize(new java.awt.Dimension(1100, 900));

        pnlPrincipal.setBackground(new java.awt.Color(237, 229, 222));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1100, 675));

        panelFiltros.setBackground(new java.awt.Color(217, 217, 217));

        txxNombreCliente.setText("NombreCliente");
        txxNombreCliente.setPreferredSize(new java.awt.Dimension(220, 35));

        btnBuscar.setText("Buscar");
        btnBuscar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBuscar.setPreferredSize(new java.awt.Dimension(150, 35));
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        cmbxEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelFiltrosLayout = new javax.swing.GroupLayout(panelFiltros);
        panelFiltros.setLayout(panelFiltrosLayout);
        panelFiltrosLayout.setHorizontalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txxNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cmbxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFiltrosLayout.setVerticalGroup(
            panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txxNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbxEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Venta", "Cliente", "Piezas", "Importe", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPedidos);

        btnActualizarPedido.setBackground(new java.awt.Color(191, 64, 43));
        btnActualizarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarPedido.setText("Actualizar Pedido");
        btnActualizarPedido.addActionListener(this::btnActualizarPedidoActionPerformed);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDetallesPedido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(panelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(pnlDetallesPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPedidoActionPerformed
        control.procesarPedido();
    }//GEN-LAST:event_btnActualizarPedidoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombre = txxNombreCliente.getText().trim();
        if (nombre.equals(PLACEHOLDER_TEXT) || nombre.equals("NombreCliente")) {
            nombre = ""; 
        }
        
        String estadoSeleccionado = (String) cmbxEstados.getSelectedItem();
        itson.org.ghosttracks.enums.EstadoPedidoDTO estado = null;
        
        if (estadoSeleccionado != null && !estadoSeleccionado.equals("Todos los estados")) {
            estado = itson.org.ghosttracks.enums.EstadoPedidoDTO.valueOf(estadoSeleccionado);
        }

        control.aplicarFiltros(nombre, estado, this);
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnActualizarPedido;
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnBuscar;
    private javax.swing.JComboBox<String> cmbxEstados;
    private javax.swing.JScrollPane jScrollPane1;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelFiltros;
    private itson.org.ghosttracks.utilerias.pnlDetallesPedido pnlDetallesPedido1;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTable tblPedidos;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado txxNombreCliente;
    // End of variables declaration//GEN-END:variables

    public void llenarTabla(List<PedidoDTO> pedidos) {
        DefaultTableModel modelo = (DefaultTableModel) tblPedidos.getModel();
        modelo.setRowCount(0);

        for (PedidoDTO pedido : pedidos) {
            Object[] fila = new Object[5]; 

            fila[0] = pedido.getIdPedido(); 
            fila[1] = pedido.getCliente().getNombres()+" "+pedido.getCliente().getApellidoPaterno();
            int totalPiezas = 0;
            if (pedido.getCarrito() != null && pedido.getCarrito().getProductos() != null) {
                for (ItemCarritoDTO item : pedido.getCarrito().getProductos()) {
                    totalPiezas += item.getCantidad();
                }
            }
            fila[2] = totalPiezas;
            fila[3] = String.format("$%.2f", pedido.getCarrito().getTotal());
            fila[4] = pedido.getEstado() != null ? pedido.getEstado().name() : "Sin estado";

            modelo.addRow(fila);
        }
    }
    
    private void configurarEventosTabla() {
        tblPedidos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tblPedidos.getSelectedRow() != -1) {
                Long idPedido = (Long) tblPedidos.getValueAt(tblPedidos.getSelectedRow(), 0);
                control.seleccionarPedido(idPedido, this);
            }
        });
    }
    
    public void mostrarDetallesDelPedido(PedidoDTO pedido) {
        pnlDetallesPedido1.cargarDetalles(pedido);
    }
    
    private void configurarFiltros() {
        cmbxEstados.removeAllItems();
        cmbxEstados.addItem("Todos los estados");
        for (itson.org.ghosttracks.enums.EstadoPedidoDTO estado : itson.org.ghosttracks.enums.EstadoPedidoDTO.values()) {
            cmbxEstados.addItem(estado.name());
        }
    }
    
    private void configurarPlaceholder() {
        txxNombreCliente.setText(PLACEHOLDER_TEXT);
        txxNombreCliente.setForeground(new Color(153, 153, 153)); 
        txxNombreCliente.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txxNombreCliente.getText().equals(PLACEHOLDER_TEXT)) {
                    txxNombreCliente.setText("");
                    txxNombreCliente.setForeground(new java.awt.Color(0, 0, 0)); 
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txxNombreCliente.getText().trim().isEmpty()) {
                    txxNombreCliente.setText(PLACEHOLDER_TEXT);
                    txxNombreCliente.setForeground(new java.awt.Color(153, 153, 153)); 
                }
            }
        });
    }
}
