
package itson.org.ghosttracks.presentacion;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author oliro
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    private JScrollPane scrollContenido; 
    private JPanel panelDerecho;
    private JPanel headerActual;
    private JPanel menuActual;
    
    public VentanaPrincipal() {
        initComponents();
        
        this.setLayout(new BorderLayout());
        
        panelDerecho = new JPanel(new BorderLayout());
        
        scrollContenido = new JScrollPane();
        scrollContenido.setBorder(null); 
        scrollContenido.getVerticalScrollBar().setUnitIncrement(16); // Hace que vaya más rápido 
        scrollContenido.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollContenido.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        panelDerecho.add(scrollContenido, BorderLayout.CENTER);
        
        this.add(panelDerecho, BorderLayout.CENTER);
    }
    
    public void fijarMenuLateral(JPanel menu) {
        BorderLayout layout = (BorderLayout) this.getContentPane().getLayout();
        java.awt.Component menuAntiguo = layout.getLayoutComponent(BorderLayout.WEST);
        if (menuAntiguo != null) {
            this.remove(menuAntiguo);
        }
        
        this.menuActual = menu; 
        this.add(this.menuActual, BorderLayout.WEST);
        this.revalidate();
    }
    
    public void fijarHeader(JPanel header) {
        if (headerActual != null) {
            panelDerecho.remove(headerActual);
        }
        headerActual = header;
        panelDerecho.add(headerActual, BorderLayout.NORTH);
        panelDerecho.revalidate();
    }
    
    public void cambiarPantalla(JPanel nuevaPantalla) {
        scrollContenido.setViewportView(nuevaPantalla); 
        this.revalidate(); 
        this.repaint(); 
    }
    
    public void limpiarMenuYHeader() {
        BorderLayout layout = (BorderLayout) this.getContentPane().getLayout(); 
        java.awt.Component menu = layout.getLayoutComponent(BorderLayout.WEST);
        if (menu != null) {
            this.remove(menu);
        }
        if (headerActual != null) {
            panelDerecho.remove(headerActual);
            headerActual = null;
        }
        this.revalidate();
        this.repaint();
    }
    
    public void mostrarMensaje(String msj, boolean esError) {
        int tipo = esError ? JOptionPane.ERROR_MESSAGE : JOptionPane.INFORMATION_MESSAGE;
        JOptionPane.showMessageDialog(this, msj, "Sistema", tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ghost Tracks");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
