
package itson.org.ghosttracks.presentacion.cliente;

import itson.org.ghosttracks.mocks.ProductosMockDAO;
import itson.org.ghosttracks.enums.TipoProducto;
import itson.org.ghosttracks.utilerias.pnlProductoCatalogo;
import itson.org.ghosttracks.controladores.ControlVentaEnLinea;
import itson.org.ghosttracks.dtos.ProductoDTO;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author oliro
 */
public class PantallaInicioCliente extends javax.swing.JPanel {

    private final ControlVentaEnLinea control;
    
    public PantallaInicioCliente(ControlVentaEnLinea ctrl) {
        this.control = ctrl;
        initComponents();
        control.llenarCatalogo(this);
        configurarFiltros();
        inicializarFiltrosGeneros();
        
    }

    private void configurarFiltros() {
        pnlVinilos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        pnlVinilos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                control.obtenerCatalogoPorTipo(PantallaInicioCliente.this, TipoProducto.VINILO);
            }
        });
        
        pnlCds.setCursor(new Cursor(Cursor.HAND_CURSOR));
        pnlCds.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                control.obtenerCatalogoPorTipo(PantallaInicioCliente.this, TipoProducto.CD);
            }
        });
        
        pnlCassettes.setCursor(new Cursor(Cursor.HAND_CURSOR));
        pnlCassettes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                control.obtenerCatalogoPorTipo(PantallaInicioCliente.this, TipoProducto.CASSETTE);
            }
        });

        lblTodos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblTodos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
            }
        });
    }
    
    public void cargarCatalogo(List<ProductoDTO> listaProductos) {
        pnlCatalogo.removeAll(); 
        
        pnlCatalogo.setLayout(new java.awt.BorderLayout());
        
        JPanel pnlCuadricula = new JPanel();
        pnlCuadricula.setLayout(new GridLayout(0, 3, 5, 5));
        pnlCuadricula.setOpaque(false);
        
        if (listaProductos != null && !listaProductos.isEmpty()) {
            for (ProductoDTO producto : listaProductos) {
                 pnlProductoCatalogo tarjeta = new pnlProductoCatalogo(producto, control);
                 tarjeta.setVisible(true);
                 pnlCuadricula.add(tarjeta); 
            }
            int faltantes = 3 - (listaProductos.size() % 3);
            if (faltantes == 3) {
            }
            for (int i = 0; i < faltantes; i++) {
                JPanel panelFantasma = new JPanel();
                panelFantasma.setOpaque(false);
                pnlCuadricula.add(panelFantasma);
            }
        }
        
        pnlCatalogo.add(pnlCuadricula, BorderLayout.NORTH);

        pnlCatalogo.revalidate();
        pnlCatalogo.repaint();
    }
    
    private void inicializarFiltrosGeneros() {
        lblTodos.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lblTodos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                control.llenarCatalogo(PantallaInicioCliente.this);
            }
        });

        configurarEtiquetaFiltro(lblRock, "Rock");
        configurarEtiquetaFiltro(lblAlternativo, "Alternativo");
        configurarEtiquetaFiltro(lblPop, "Pop");
        configurarEtiquetaFiltro(lblHipHop, "Hip hop");
        configurarEtiquetaFiltro(lblKpop, "K-pop");
        configurarEtiquetaFiltro(lblJazz, "Jazz");
        configurarEtiquetaFiltro(lblUrbana, "Urbana");
        configurarEtiquetaFiltro(lblRegionalMexicana, "Regional Mexicana");
        configurarEtiquetaFiltro(lblTropical, "Tropical");
    }
    
    private void configurarEtiquetaFiltro(JLabel etiqueta, String genero) {
        etiqueta.setCursor(new Cursor(Cursor.HAND_CURSOR));
        etiqueta.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                control.obtenerCatalogoPorGenero(PantallaInicioCliente.this, genero);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlContenido = new javax.swing.JPanel();
        pnlVinilos = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelRedondeado3 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        jLabel7 = new javax.swing.JLabel();
        lblTodos = new javax.swing.JLabel();
        lblRock = new javax.swing.JLabel();
        lblAlternativo = new javax.swing.JLabel();
        lblPop = new javax.swing.JLabel();
        lblHipHop = new javax.swing.JLabel();
        lblKpop = new javax.swing.JLabel();
        lblJazz = new javax.swing.JLabel();
        lblUrbana = new javax.swing.JLabel();
        lblRegionalMexicana = new javax.swing.JLabel();
        lblTropical = new javax.swing.JLabel();
        pnlCds = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlCassettes = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlCatalogo = new javax.swing.JPanel();

        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlContenido.setBackground(new java.awt.Color(237, 229, 222));
        pnlContenido.setPreferredSize(new java.awt.Dimension(1090, 1256));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vinilos");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoVinilo.png"))); // NOI18N

        javax.swing.GroupLayout pnlVinilosLayout = new javax.swing.GroupLayout(pnlVinilos);
        pnlVinilos.setLayout(pnlVinilosLayout);
        pnlVinilosLayout.setHorizontalGroup(
            pnlVinilosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVinilosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVinilosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlVinilosLayout.setVerticalGroup(
            pnlVinilosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVinilosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Géneros");

        lblTodos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTodos.setText("Todos");

        lblRock.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblRock.setText("Rock");

        lblAlternativo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAlternativo.setText("Alternativo");

        lblPop.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPop.setText("Pop");

        lblHipHop.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHipHop.setText("Hip hop");

        lblKpop.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblKpop.setText("K-pop");

        lblJazz.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblJazz.setText("Jazz");

        lblUrbana.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUrbana.setText("Urbana");

        lblRegionalMexicana.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblRegionalMexicana.setText("Regional Mexicana");

        lblTropical.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTropical.setText("Tropical");

        javax.swing.GroupLayout panelRedondeado3Layout = new javax.swing.GroupLayout(panelRedondeado3);
        panelRedondeado3.setLayout(panelRedondeado3Layout);
        panelRedondeado3Layout.setHorizontalGroup(
            panelRedondeado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRedondeado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedondeado3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(lblTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAlternativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHipHop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKpop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJazz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUrbana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRegionalMexicana, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(lblTropical, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelRedondeado3Layout.setVerticalGroup(
            panelRedondeado3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlternativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHipHop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKpop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJazz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUrbana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegionalMexicana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTropical)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoCD.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CDs");

        javax.swing.GroupLayout pnlCdsLayout = new javax.swing.GroupLayout(pnlCds);
        pnlCds.setLayout(pnlCdsLayout);
        pnlCdsLayout.setHorizontalGroup(
            pnlCdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCdsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCdsLayout.setVerticalGroup(
            pnlCdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCdsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cassettes");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconoCassette.png"))); // NOI18N

        javax.swing.GroupLayout pnlCassettesLayout = new javax.swing.GroupLayout(pnlCassettes);
        pnlCassettes.setLayout(pnlCassettesLayout);
        pnlCassettesLayout.setHorizontalGroup(
            pnlCassettesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCassettesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCassettesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCassettesLayout.setVerticalGroup(
            pnlCassettesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCassettesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pnlCatalogo.setBackground(new java.awt.Color(237, 229, 222));
        pnlCatalogo.setPreferredSize(new java.awt.Dimension(775, 1095));

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelRedondeado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addComponent(pnlVinilos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCassettes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenidoLayout.createSequentialGroup()
                        .addGroup(pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlVinilos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCassettes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelRedondeado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(pnlContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAlternativo;
    private javax.swing.JLabel lblHipHop;
    private javax.swing.JLabel lblJazz;
    private javax.swing.JLabel lblKpop;
    private javax.swing.JLabel lblPop;
    private javax.swing.JLabel lblRegionalMexicana;
    private javax.swing.JLabel lblRock;
    private javax.swing.JLabel lblTodos;
    private javax.swing.JLabel lblTropical;
    private javax.swing.JLabel lblUrbana;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado3;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlCassettes;
    private javax.swing.JPanel pnlCatalogo;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlCds;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlPrincipal;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlVinilos;
    // End of variables declaration//GEN-END:variables
}
