
package itson.org.ghosttracks.presentacion.cliente;

import itson.org.ghosttracks.controladores.ControlVentaEnLinea;
import itson.org.ghosttracks.dtos.ProductoDTO;
import itson.org.ghosttracks.utilerias.pnlProductoSugerencia;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author oliro
 */
public class PantallaVistaProducto extends javax.swing.JPanel {

    private ControlVentaEnLinea control;
    private ProductoDTO producto;
    private Integer cantidadActual = 1;
    
    public PantallaVistaProducto(ControlVentaEnLinea control, ProductoDTO producto) {
        this.control = control;
        this.producto = producto;
        initComponents();
        cargarDatosProducto();
        cargarSugerenciasAlAzar();
        configurarBotonesCantidad();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlFondo = new javax.swing.JPanel();
        panelRedondeado1 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        panelRedondeado4 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblImgProducto = new javax.swing.JLabel();
        pnlSugerenciasFondo = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        pnlSugerencias = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonRedondeado1 = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        panelRedondeado5 = new itson.org.ghosttracks.utilerias.PanelRedondeado();
        lblNombreProducto = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        textFieldRedondeado1 = new itson.org.ghosttracks.utilerias.TextFieldRedondeado();
        btnMenos = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        btnMas = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        lblUnidad = new javax.swing.JLabel();
        AniadirProducto = new itson.org.ghosttracks.utilerias.BotonRedondeado();
        lblSetlist = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1100, 675));

        pnlFondo.setBackground(new java.awt.Color(237, 229, 222));
        pnlFondo.setPreferredSize(new java.awt.Dimension(1100, 1150));

        panelRedondeado1.setBackground(new java.awt.Color(217, 217, 217));
        panelRedondeado1.setPreferredSize(new java.awt.Dimension(410, 410));

        panelRedondeado4.setBackground(new java.awt.Color(230, 230, 230));
        panelRedondeado4.setPreferredSize(new java.awt.Dimension(400, 400));

        lblImgProducto.setBackground(new java.awt.Color(255, 51, 51));
        lblImgProducto.setForeground(new java.awt.Color(255, 102, 102));
        lblImgProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgProducto.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout panelRedondeado4Layout = new javax.swing.GroupLayout(panelRedondeado4);
        panelRedondeado4.setLayout(panelRedondeado4Layout);
        panelRedondeado4Layout.setHorizontalGroup(
            panelRedondeado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRedondeado4Layout.setVerticalGroup(
            panelRedondeado4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelRedondeado1Layout = new javax.swing.GroupLayout(panelRedondeado1);
        panelRedondeado1.setLayout(panelRedondeado1Layout);
        panelRedondeado1Layout.setHorizontalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRedondeado4, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRedondeado1Layout.setVerticalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRedondeado4, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSugerenciasFondo.setBackground(new java.awt.Color(217, 217, 217));
        pnlSugerenciasFondo.setPreferredSize(new java.awt.Dimension(1040, 800));

        pnlSugerencias.setBackground(new java.awt.Color(217, 217, 217));
        pnlSugerencias.setMaximumSize(new java.awt.Dimension(559, 716));
        pnlSugerencias.setMinimumSize(new java.awt.Dimension(559, 716));
        pnlSugerencias.setPreferredSize(new java.awt.Dimension(559, 716));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Tambien podría interesarte...");

        javax.swing.GroupLayout pnlSugerenciasFondoLayout = new javax.swing.GroupLayout(pnlSugerenciasFondo);
        pnlSugerenciasFondo.setLayout(pnlSugerenciasFondoLayout);
        pnlSugerenciasFondoLayout.setHorizontalGroup(
            pnlSugerenciasFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSugerenciasFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlSugerencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSugerenciasFondoLayout.setVerticalGroup(
            pnlSugerenciasFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSugerenciasFondoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSugerencias, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonRedondeado1.setText("Volver");
        botonRedondeado1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRedondeado1.addActionListener(this::botonRedondeado1ActionPerformed);

        panelRedondeado5.setBackground(new java.awt.Color(217, 217, 217));
        panelRedondeado5.setPreferredSize(new java.awt.Dimension(440, 322));

        lblNombreProducto.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        lblNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreProducto.setText("Nombre del producto");
        lblNombreProducto.setToolTipText("");
        lblNombreProducto.setPreferredSize(new java.awt.Dimension(400, 44));

        lblArtista.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        lblArtista.setForeground(new java.awt.Color(102, 102, 102));
        lblArtista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArtista.setText("Artista");

        lblPrecio.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(51, 51, 51));
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("$00.00");
        lblPrecio.setToolTipText("");
        lblPrecio.setPreferredSize(new java.awt.Dimension(200, 35));

        textFieldRedondeado1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldRedondeado1.setText("Cantidad");
        textFieldRedondeado1.setPreferredSize(new java.awt.Dimension(100, 35));

        btnMenos.setText("-");
        btnMenos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnMas.setText("+");
        btnMas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblUnidad.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblUnidad.setForeground(new java.awt.Color(102, 102, 102));
        lblUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUnidad.setText("pzas.");

        AniadirProducto.setBackground(new java.awt.Color(230, 94, 7));
        AniadirProducto.setText("Añadir al carrito");
        AniadirProducto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        AniadirProducto.addActionListener(this::AniadirProductoActionPerformed);

        javax.swing.GroupLayout panelRedondeado5Layout = new javax.swing.GroupLayout(panelRedondeado5);
        panelRedondeado5.setLayout(panelRedondeado5Layout);
        panelRedondeado5Layout.setHorizontalGroup(
            panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado5Layout.createSequentialGroup()
                        .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado5Layout.createSequentialGroup()
                        .addComponent(lblNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado5Layout.createSequentialGroup()
                        .addComponent(lblUnidad)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado5Layout.createSequentialGroup()
                        .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AniadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado5Layout.createSequentialGroup()
                        .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
        );
        panelRedondeado5Layout.setVerticalGroup(
            panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRedondeado5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUnidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AniadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        lblSetlist.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSetlist.setForeground(new java.awt.Color(102, 102, 102));
        lblSetlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSetlist.setText("setlist");
        lblSetlist.setPreferredSize(new java.awt.Dimension(252, 200));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblSetlist, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addComponent(panelRedondeado1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRedondeado5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSugerenciasFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(panelRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSetlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(panelRedondeado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(pnlSugerenciasFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(pnlFondo);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRedondeado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRedondeado1ActionPerformed
        control.irAInicio();
    }//GEN-LAST:event_botonRedondeado1ActionPerformed

    private void AniadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AniadirProductoActionPerformed
        control.agregarProductoCarrito(producto, cantidadActual);
        control.mostrarMensaje("Producto agregado con exito", false);
        
        cantidadActual = 1;
        textFieldRedondeado1.setText(String.valueOf(cantidadActual));
    }//GEN-LAST:event_AniadirProductoActionPerformed

    private void cargarDatosProducto() {
        lblNombreProducto.setText(producto.getNombre());
        lblArtista.setText(producto.getArtista());
        lblPrecio.setText(String.format("$%.2f", producto.getPrecio()));

        if (producto.getSetlist() != null && !producto.getSetlist().isEmpty()) {
            String canciones = String.join("<br>", producto.getSetlist());
            lblSetlist.setText("<html><div style='text-align:center;'>" + canciones + "</div></html>");
        } else {
            lblSetlist.setText("Setlist no disponible");
        }

        try {
            String nombreArchivo = producto.getImgProducto();
            String ruta = "/imgVistaProducto/" + nombreArchivo;
            
            if (ruta != null && !ruta.isEmpty()) {
                java.net.URL urlImagenLocal = getClass().getResource(ruta);
                if (urlImagenLocal != null) {
                    java.awt.Image imagenOriginal = javax.imageio.ImageIO.read(urlImagenLocal);
                    java.awt.Image imagenEscalada = imagenOriginal.getScaledInstance(407, 407, java.awt.Image.SCALE_SMOOTH);
                    lblImgProducto.setIcon(new javax.swing.ImageIcon(imagenEscalada));
                    lblImgProducto.setText(""); 
                } else {
                    throw new Exception("No se encontró la ruta en el proyecto");
                }
            }
        } catch (Exception e) {
            System.out.println("Error cargando imagen principal de: " + producto.getNombre());
            lblImgProducto.setIcon(null);
            lblImgProducto.setText("Imagen no disp.");
        }
    }
    
    private void cargarSugerenciasAlAzar() {
        try {
            List<ProductoDTO> todosLosProductos = control.obtenerCatalogoCompleto(); 

            if (todosLosProductos != null && !todosLosProductos.isEmpty()) {

                List<ProductoDTO> productosFiltrados = new java.util.ArrayList<>();
                for (ProductoDTO p : todosLosProductos) {
                    if (!p.getNombre().equals(this.producto.getNombre())) {
                        productosFiltrados.add(p);
                    }
                }
                Collections.shuffle(productosFiltrados);

                pnlSugerencias.removeAll(); 

                int cantidadSugerencias = Math.min(4, productosFiltrados.size());

                for (int i = 0; i < cantidadSugerencias; i++) {
                    ProductoDTO productoAlAzar = productosFiltrados.get(i);

                    pnlProductoSugerencia tarjeta = new pnlProductoSugerencia(productoAlAzar, this.control);
                    pnlSugerencias.add(tarjeta);
                }

                pnlSugerencias.revalidate();
                pnlSugerencias.repaint();
            }
        } catch (Exception ex) {
            System.out.println("Error al cargar sugerencias: " + ex.getMessage());
        }
    }
    
    private void configurarBotonesCantidad() {
        textFieldRedondeado1.setText(String.valueOf(cantidadActual));
        textFieldRedondeado1.setEditable(false); 
        
        btnMenos.addActionListener(evt -> {
            if (cantidadActual > 1) { 
                cantidadActual--;
                textFieldRedondeado1.setText(String.valueOf(cantidadActual));
            }
        });
        
        btnMas.addActionListener(evt -> {
            cantidadActual++;
            textFieldRedondeado1.setText(String.valueOf(cantidadActual));
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itson.org.ghosttracks.utilerias.BotonRedondeado AniadirProducto;
    private itson.org.ghosttracks.utilerias.BotonRedondeado botonRedondeado1;
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnMas;
    private itson.org.ghosttracks.utilerias.BotonRedondeado btnMenos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblImgProducto;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSetlist;
    private javax.swing.JLabel lblUnidad;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado1;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado4;
    private itson.org.ghosttracks.utilerias.PanelRedondeado panelRedondeado5;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlSugerencias;
    private itson.org.ghosttracks.utilerias.PanelRedondeado pnlSugerenciasFondo;
    private itson.org.ghosttracks.utilerias.TextFieldRedondeado textFieldRedondeado1;
    // End of variables declaration//GEN-END:variables
}
